### ISSUE TITLE
Package attempts to access a package not declared in dependencies

### ISSUE THREAD

**Issue by wopian** [honeycombio/honeycomb-opentelemetry-node#206]
**Versions**

0.4.0 (as a dependency of a dependency)

**Steps to reproduce**

1. Use Yarn v3 or Yarn v4 as your package manager
2. Install dependencies
3. Dependency installation fails due to unprivileged access

**Additional context**

This package is used in the following 2 locations:

- https://github.com/honeycombio/honeycomb-opentelemetry-node/blob/a2da97851f6d443a8ac4fafe3844c38cb8912b7c/src/composite-exporter.ts#L1

- https://github.com/honeycombio/honeycomb-opentelemetry-node/blob/a2da97851f6d443a8ac4fafe3844c38cb8912b7c/src/local-exporter.ts#L1

It is not listed in the package's dependency manifest:

- https://github.com/honeycombio/honeycomb-opentelemetry-node/blob/main/package.json#L61-L73

```
Error: @honeycombio/opentelemetry-node tried to access @opentelemetry/core, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @opentelemetry/core
Required by: @honeycombio/opentelemetry-node@npm:0.4.0 (via /home/runner/.yarn/berry/cache/@honeycombio-opentelemetry-node-npm-0.4.0-ed4bb5d28e-8.zip/node_modules/@honeycombio/opentelemetry-node/dist/src/)

Require stack:
- /home/runner/.yarn/berry/cache/@honeycombio-opentelemetry-node-npm-0.4.0-ed4bb5d28e-8.zip/node_modules/@honeycombio/opentelemetry-node/dist/src/local-exporter.js
- /home/runner/.yarn/berry/cache/@honeycombio-opentelemetry-node-npm-0.4.0-ed4bb5d28e-8.zip/node_modules/@honeycombio/opentelemetry-node/dist/src/baggage-span-processor.js
- /home/runner/.yarn/berry/cache/@honeycombio-opentelemetry-node-npm-0.4.0-ed4bb5d28e-8.zip/node_modules/@honeycombio/opentelemetry-node/dist/src/opentelemetry-node.js
- /home/runner/.yarn/berry/cache/@honeycombio-opentelemetry-node-npm-0.4.0-ed4bb5d28e-8.zip/node_modules/@honeycombio/opentelemetry-node/dist/src/index.js
    at require$$0.Module._resolveFilename (/tmp/xfs-86c9d407/dlx-2236/.pnp.cjs:20904:13)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at require$$0.Module._load (/tmp/xfs-86c9d407/dlx-2236/.pnp.cjs:20793:31)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/runner/.yarn/berry/cache/@honeycombio-opentelemetry-node-npm-0.4.0-ed4bb5d28e-8.zip/node_modules/@honeycombio/opentelemetry-node/dist/src/local-exporter.js:7:16)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at require$$0.Module._extensions..js (/tmp/xfs-86c9d407/dlx-2236/.pnp.cjs:20948:33)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
```

**Comment by wopian** [comment]
Thank you :)
